### ISSUE TITLE
Does Kruise has Kubernetes version requirement?

### ISSUE THREAD

**Issue by candyleer** [openkruise/kruise#108]
I cannot run `kruise-manager-controller` in `1.10.5`,but in `1.12.4` works well.
here is the error by ` kubectl logs kruise-controller-manager-0 -n kruise-system` :
```
I0801 14:25:04.106247       1 statefulset_controller.go:184] Finished syncing statefulset "xxxx/aabb-gz01a-blue" (1.597937ms)
E0801 14:25:04.106346       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/stateful_set_utils.go:246
/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/stateful_set_control.go:324
/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/stateful_set_control.go:93
/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/statefulset_controller.go:281
/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/statefulset_controller.go:213
/go/src/github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/go/src/github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x116c203]

goroutine 242 [running]:
github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x13142a0, 0x1ebee20)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/openkruise/kruise/pkg/controller/statefulset.newVersionedStatefulSetPod(0xc4201d5200, 0xc4201d5b00, 0xc420cfece0, 0x1a, 0xc420cfece0, 0x1a, 0x0, 0x0)
	/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/stateful_set_utils.go:246 +0x83
github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).updateStatefulSet(0xc4203591c0, 0xc4201d4000, 0xc420639308, 0xc420639308, 0x0, 0x0, 0x0, 0x0, 0xc420e48bb0, 0x1, ...)
	/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/stateful_set_control.go:324 +0x713
github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).UpdateStatefulSet(0xc4203591c0, 0xc4201d4000, 0x0, 0x0, 0x0, 0x3, 0x1ef2488)
	/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/stateful_set_control.go:93 +0x184
github.com/openkruise/kruise/pkg/controller/statefulset.(*ReconcileStatefulSet).syncStatefulSet(0xc42006ebe0, 0xc420b22400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/statefulset_controller.go:281 +0x1ac
github.com/openkruise/kruise/pkg/controller/statefulset.(*ReconcileStatefulSet).Reconcile(0xc42006ebe0, 0xc420e0f4f0, 0xb, 0xc420e0f4d0, 0xf, 0x1ed3a00, 0x0, 0x0, 0x0)
	/go/src/github.com/openkruise/kruise/pkg/controller/statefulset/statefulset_controller.go:213 +0x4ff
github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc420170960, 0x0)
	/go/src/github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x188
github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4204060d0)
	/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4204060d0, 0x3b9aca00, 0x0, 0x1, 0xc42071ce40)
	/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4204060d0, 0x3b9aca00, 0xc42071ce40)
	/go/src/github.com/openkruise/kruise/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/openkruise/kruise/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x35b
```

**Comment by jian-he** [comment]
hmm, it shouldn't be, the default value is actually set in
https://github.com/openkruise/kruise/blob/f297eaa8b1c3b7d8c5efe677a7b2ef62b3e86ec6/pkg/webhook/default_server/statefulset/mutating/statefulset_create_update_handler.go#L123

@FillZpp

**Comment by candyleer** [comment]
This issue also exist in `v0.1.0`

**Comment by FillZpp** [comment]
@candyleer Have you enabled `MutatingAdmissionWebhook` and `ValidatingAdmissionWebhook` admission plugins in your kube-apiserver?

**Comment by candyleer** [comment]
@FillZpp  It seems it's enabled in >=1.10.x by default

**Comment by candyleer** [comment]
when I set the `partition=0` manually,another error found:
```
E0813 02:38:11.484076       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="the server could not find the requested resource (put statefulsets.apps.kruise.io aabb-gz01a-green)"  "controller"="statefulset-controller" "request"={"Namespace":"default","Name":"aabb-gz01a-green"}
```

**Comment by Fei-Guo** [comment]
> the server could not find the requested resource

If the problem still exists, can you post the full error log?

**Comment by FillZpp** [comment]
OpenKruise only supports Kubernetes version >= 1.13+ because of CRD conversion. Note that for Kubernetes 1.13 and 1.14, users must enable CustomResourceWebhookConversion feature-gate in kube-apiserver before install or upgrade Kruise.

See https://openkruise.io/en-us/docs/quick_start.html
