### ISSUE TITLE
[BUG] Failed to new image service for containerd (, unix:///hostvarrun/containerd/containerd.sock): failed to fetch cri-containerd status: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

### ISSUE THREAD

**Issue by LIRUILONGS** [openkruise/kruise#1196]
**What happened**:

在使用过 heml 部署 时 DS 无法正常启动，一直在重启
```bash
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$kubectl get all -n kruise-system
NAME                                             READY   STATUS             RESTARTS      AGE
pod/kruise-controller-manager-7dc584559b-j8j78   1/1     Running            0             2m31s
pod/kruise-controller-manager-7dc584559b-r954q   1/1     Running            0             2m32s
pod/kruise-daemon-24fgt                          0/1     CrashLoopBackOff   4 (9s ago)    2m33s
pod/kruise-daemon-7t5q6                          0/1     CrashLoopBackOff   4 (11s ago)   2m32s
pod/kruise-daemon-fbt8m                          0/1     CrashLoopBackOff   4 (16s ago)   2m33s
pod/kruise-daemon-fc8xr                          0/1     CrashLoopBackOff   4 (11s ago)   2m32s
pod/kruise-daemon-kjjfd                          0/1     CrashLoopBackOff   4 (15s ago)   2m32s
pod/kruise-daemon-krs9s                          0/1     CrashLoopBackOff   4 (17s ago)   2m33s
pod/kruise-daemon-lb5nq                          0/1     CrashLoopBackOff   4 (15s ago)   2m32s
pod/kruise-daemon-zpfzg                          0/1     CrashLoopBackOff   3 (32s ago)   2m32s
```
日志提示

```bash
........
I0228 07:42:33.035374 1 request.go:597] Waited for 1.098924044s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/management.cattle.io/v3?timeout=32s
I0228 07:42:33.085460 1 request.go:597] Waited for 1.14899442s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/project.cattle.io/v3?timeout=32s
I0228 07:42:33.135453 1 request.go:597] Waited for 1.100261177s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/coordination.k8s.io/v1?timeout=32s
W0228 07:42:33.140079 1 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
E0228 07:42:33.140161 1 factory.go:224] /hostvarrun/docker.sock exists, but not found /hostvarrun/dockershim.sock
W0228 07:42:33.336170 1 factory.go:113] Failed to new image service for containerd (, unix:///hostvarrun/containerd/containerd.sock): failed to fetch cri-containerd status: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
W0228 07:42:33.336612 1 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x19a8c75]
goroutine 1 [running]:
github.com/openkruise/kruise/pkg/daemon/imagepuller.NewController({{0xc00005206a, 0x1b}, 0xc000482e70, {0x218f7c8, 0xc0000a11f0}, {0x218f6f8, 0xc0005ddcc0}, {0x0, 0x0}, 0xc00043c1e0}, ...)
    /workspace/pkg/daemon/imagepuller/imagepuller_controller.go:96 +0x3d5
github.com/openkruise/kruise/pkg/daemon.NewDaemon(0xc0001a2240, {0x7ffc90a37c92, 0x6})
    /workspace/pkg/daemon/daemon.go:140 +0x505
main.main()
    /workspace/cmd/daemon/main.go:64 +0x278
```

**What you expected to happen**:

我希望它可以正常部署

**How to reproduce it (as minimally and precisely as possible)**:

部署时的操作

```bash
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$helm install kruise openkruise/kruise  --set  manager.image.repository=openkruise-registry.cn-shanghai.cr.aliyuncs.com/openkruise/kruise-manager
NAME: kruise
LAST DEPLOYED: Tue Feb 28 15:25:34 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$helm ls
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kruise  default         1               2023-02-28 15:25:34.865181878 +0800 CST deployed        kruise-1.3.0    1.3.0
```

**Anything else we need to know?**:

我想可能是它找不到 runtime，我可以在部署时指定 runtime 嘛？， 比如指定 `--cri-socket /var/run/cri-dockerd.sock`  ,在 我的集群中 使用 docker/cri-docker 作为 CRI 

**Environment**:
- Kruise version:
```bash
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$helm ls
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kruise  default         1               2023-02-28 15:25:34.865181878 +0800 CST deployed        kruise-1.3.0    1.3.0
```
- Kubernetes version (use `kubectl version`):
```bash
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$helm version
version.BuildInfo{Version:"v3.11.0-rc.1", GitCommit:"9d8fee155bd7e7d3c1390f4076d9271a1147dce5", GitTreeState:"clean", GoVersion:"go1.18.9"}
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.25.1
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$
```
- Install details (e.g. helm install args):
```bash
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$helm install kruise openkruise/kruise  --set  manager.image.repository=openkruise-registry.cn-shanghai.cr.aliyuncs.com/openkruise/kruise-manager
```
- Others:
在 我的集群中 使用 docker/cri-docker 作为 CRI

**Comment by chengleqi** [comment]
你可以试试加一下 `daemon.socketLocation`这个参数
https://openkruise.io/zh/docs/installation#k3s-%E5%AE%89%E8%A3%85%E5%8F%82%E6%95%B0

**Comment by LIRUILONGS** [comment]
@chengleqi  非常感谢 :) cri 接口实现目录没有变化，但是在 `daemon.socketLocation` 下面，发现了 `daemon.socketFile` ： 指定 socketLocation 目录下的 socket 文件名 (如果你使用的 CRI 类型不是 containerd/docker/pouch/cri-o)。 它适合我 ^_^
```bash
┌──[root@vms100.liruilongs.github.io]-[~/ansible/openkruise]
└─$helm install  kruise openkruise/kruise  --set  manager.image.repository=openkruise-registry.cn-shanghai.cr.aliyuncs.com/openkruise/kruise-manager,daemon.socketFile=/var/run/cri-dockerd.sock
```

**Comment by ysicing** [comment]
@chengleqi k3s 1.24版本 + docker貌似配置不生效

```yaml
daemon:
  socketLocation: "/var/run/k3s"
  socketFile: "/var/run/k3s/cri-dockerd/cri-dockerd.sock"
```

日志：

```
W0310 11:38:14.769425       1 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
E0310 11:38:14.769456       1 factory.go:189] Failed to stat the CRI socket /hostvarrun//var/run/k3s/cri-dockerd/cri-dockerd.sock with given flag: stat /hostvarrun//var/run/k3s/cri-dockerd/cri-dockerd.sock: no such file or directory
F0310 11:38:14.769477       1 main.go:66] Failed to new daemon: failed to new runtime factory: not found container runtime sock
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
```

**Comment by ysicing** [comment]
> @chengleqi k3s 1.24版本 + docker貌似配置不生效
> 
> ```yaml
> daemon:
>   socketLocation: "/var/run/k3s"
>   socketFile: "/var/run/k3s/cri-dockerd/cri-dockerd.sock"
> ```
> 
> 日志：
> 
> ```
> W0310 11:38:14.769425       1 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
> E0310 11:38:14.769456       1 factory.go:189] Failed to stat the CRI socket /hostvarrun//var/run/k3s/cri-dockerd/cri-dockerd.sock with given flag: stat /hostvarrun//var/run/k3s/cri-dockerd/cri-dockerd.sock: no such file or directory
> F0310 11:38:14.769477       1 main.go:66] Failed to new daemon: failed to new runtime factory: not found container runtime sock
> goroutine 1 [running]:
> k8s.io/klog/v2.stacks(0x1)
> ```

看代码 https://github.com/openkruise/kruise/blob/fc4aac7abec7513ffaded67631e18cc0768d882b/pkg/daemon/criruntime/factory.go#LL181C58-L181C58

应用需要调整成

```
daemon:
  socketLocation: "/var/run/k3s"
  socketFile: "cri-dockerd/cri-dockerd.sock"
```
