### ISSUE TITLE
Panic in reconciler if a CR was created before the controller pods

### ISSUE THREAD

**Issue by vpedosyuk** [openkruise/kruise#1502]
**What happened**:

I'd like to deploy Kruise operator and an advanced Statefulset in a single run via ArgoCD. This means that the Statefulset object will get created as soon as CRDs get installed in Kubernetes. However, it can be that the Statefulset will get created earlier than the controller pods.

As a result, the Statefulset exists but no pods are created for it:
```sh
$ kubectl get asts -n vm                            
NAME                                    DESIRED   CURRENT   UPDATED   READY   AGE
vm-victoria-metrics-cluster-vmstorage   3                                     21m

$ kubectl describe asts -n vm vm-victoria-metrics-cluster-vmstorage | yq .Events
<none>

$ kubectl describe asts -n vm vm-victoria-metrics-cluster-vmstorage | yq .Status
null
```

Then checking the controller:
```sh
$ kubectl get po -n kruise-system                                               
NAME                                        READY   STATUS             RESTARTS        AGE
kruise-controller-manager-84d74ffc4-rmlw7   0/1     CrashLoopBackOff   9 (19s ago)     24m
kruise-controller-manager-84d74ffc4-w7784   1/1     Running            9 (5m22s ago)   24m
```

And checking its logs:
```
I0207 12:53:31.479855       1 controller.go:227]  "msg"="Starting workers" "controller"="workloadspread-controller" "worker count"=3
I0207 12:53:31.480156       1 statefulset_controller.go:242] Finished syncing statefulset "vm/vm-victoria-metrics-cluster-vmstorage" (4.19518ms)
I0207 12:53:31.480331       1 controller.go:117]  "msg"="Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" "controller"="statefulset-controller" "name"="vm-victoria-metrics-cluster-vmstorage" "namespace"="vm" "object"={"name":"vm-victoria-metrics-cluster-vmstorage","namespace":"vm"} "reconcileID"="15d80311-b2f9-4fc4-ad66-05f12ba65ed4"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1982e94]

goroutine 928 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1ce9660, 0x3317c60})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/openkruise/kruise/pkg/controller/statefulset.isCurrentRevisionNeeded(0x18?, {0xc0018efe30?, 0x18?}, 0xc000078c00?, {0xc0045af308?, 0x0?, 0xc0044c3c80?})
	/workspace/pkg/controller/statefulset/stateful_set_utils.go:482 +0x94
github.com/openkruise/kruise/pkg/controller/statefulset.newVersionedStatefulSetPod(0xc0044b33b8?, 0x4ea7dd?, {0xc0018efe30, 0x2f}, {0xc0018efe30, 0x2f}, 0x1fc8da3?, {0xc0045af308, 0x3, 0x3})
	/workspace/pkg/controller/statefulset/stateful_set_utils.go:463 +0x67
github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).updateStatefulSet(0xc000694fc0, {0x234c4f8, 0xc0044791d0}, 0xc0040c1180, 0xc0005a6cd8, 0xc0005a6cd8, 0x1ea5ca0?, {0x0, 0x0, 0x0}, ...)
	/workspace/pkg/controller/statefulset/stateful_set_control.go:453 +0x12bc
github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).performUpdate(0xc003cafa40?, {0x234c4f8, 0xc0044791d0}, 0x1ea5ca0?, {0x0, 0x0, 0x0}, {0xc000013a18, 0x1, 0x1})
	/workspace/pkg/controller/statefulset/stateful_set_control.go:139 +0x1dc
github.com/openkruise/kruise/pkg/controller/statefulset.(*defaultStatefulSetControl).UpdateStatefulSet(0xc0005a1500?, {0x234c4f8, 0xc0044791d0}, 0xc0040c0c00?, {0x0, 0x0, 0x0})
	/workspace/pkg/controller/statefulset/stateful_set_control.go:115 +0x138
github.com/openkruise/kruise/pkg/controller/statefulset.(*ReconcileStatefulSet).syncStatefulSet(0xc0005eae60, {0x234c4f8, 0xc0044791d0}, 0xc0005a1500, {0x0, 0x0, 0x0})
	/workspace/pkg/controller/statefulset/statefulset_controller.go:345 +0x1af
github.com/openkruise/kruise/pkg/controller/statefulset.(*ReconcileStatefulSet).Reconcile(0xc0005eae60, {0x234c4f8, 0xc0044791d0}, {{{0xc000d0dba6?, 0x10?}, {0xc00165d800?, 0x40dc87?}}})
	/workspace/pkg/controller/statefulset/statefulset_controller.go:276 +0x4a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x234c450?, {0x234c4f8?, 0xc0044791d0?}, {{{0xc000d0dba6?, 0x1ebd500?}, {0xc00165d800?, 0x4045d4?}}})
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc001588500, {0x234c450, 0xc0007b3b00}, {0x1d92ec0?, 0xc004197720?})
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc001588500, {0x234c450, 0xc0007b3b00})
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x333
```

**What you expected to happen**:
I'd expect the controller to properly handle all related CRs even if the controller itself gets created later.

**How to reproduce it (as minimally and precisely as possible)**:
1. create CRDs (only)
2. create a CR (e.g. advanced Statefulset)
3. deploy Kruise operator

**Anything else we need to know?**:
It gets fixed if I manually delete the CR like this:
```sh
$ kubectl delete asts -n vm vm-victoria-metrics-cluster-vmstorage                               
statefulset.apps.kruise.io "vm-victoria-metrics-cluster-vmstorage" deleted
```
Then ArgoCD would automatically recreate the resource while Kruise pods were ready to watch its CRs:
```sh
$ kubectl get asts -n vm                                         
NAME                                    DESIRED   CURRENT   UPDATED   READY   AGE
vm-victoria-metrics-cluster-vmstorage   3         3         3         0       50s

$ kubectl get po -n kruise-system
NAME                                        READY   STATUS    RESTARTS         AGE
kruise-controller-manager-84d74ffc4-rmlw7   1/1     Running   10 (6m47s ago)   31m
kruise-controller-manager-84d74ffc4-w7784   1/1     Running   10 (6m19s ago)   31m

$ kubectl describe asts -n vm vm-victoria-metrics-cluster-vmstorage | yq .Events
Type    Reason            Age    From                    Message
----    ------            ----   ----                    -------
Normal  SuccessfulCreate  2m49s  statefulset-controller  create Pod vm-victoria-metrics-cluster-vmstorage-0 in StatefulSet vm-victoria-metrics-cluster-vmstorage successful
Normal  SuccessfulCreate  2m49s  statefulset-controller  create Pod vm-victoria-metrics-cluster-vmstorage-1 in StatefulSet vm-victoria-metrics-cluster-vmstorage successful
Normal  SuccessfulCreate  2m49s  statefulset-controller  create Pod vm-victoria-metrics-cluster-vmstorage-2 in StatefulSet vm-victoria-metrics-cluster-vmstorage successful

$ kubectl describe asts -n vm vm-victoria-metrics-cluster-vmstorage | yq .Status
Available Replicas: 3
Collision Count: 0
Current Replicas: 3
Current Revision: vm-victoria-metrics-cluster-vmstorage-cb64fb8f
Label Selector: app=vmstorage,app.kubernetes.io/instance=vm,app.kubernetes.io/name=victoria-metrics-cluster
Observed Generation: 1
Ready Replicas: 3
Replicas: 3
Update Revision: vm-victoria-metrics-cluster-vmstorage-cb64fb8f
Updated Available Replicas: 3
Updated Ready Replicas: 3
Updated Replicas: 3
```

**Environment**:
- Kruise version: v1.5.2
- Kubernetes version (use `kubectl version`): v1.27.9-gke.1092000
- Install details (e.g. helm install args):
```yaml
installation:
  namespace: kruise-system
  createNamespace: false # ArgoCD creates it instead

# disable features that require running an additional DaemonSet
featureGates: >-
  KruiseDaemon=false,
  DaemonWatchingPod=false
```

**Comment by zmberg** [comment]
@vpedosyuk You can't create the CR first and then deploy kruise. because, the Kruise webhook will supplement some fields that don't exist in the CR. For example, your problem above is caused by Spec.UpdateStrategy.RollingUpdate.Partition being nil.
